remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Welcome to Alan Shepherd's ePortfolio"
description: This page will host my progress as I work through my CS Capstone. 
